/** Figma MCP — SDK / API integrations logo strip */
export const veeLogoSalesforce = '/images/home-integrations/salesforce.png'
export const veeLogoShopify = '/images/tech-partners/shopify-plus.svg'
export const veeLogoSap = '/images/tech-partners/sap-hybris.svg'
export const veeLogoMagento = '/images/tech-partners/magento.svg'
export const veeLogoApplePay = '/images/tech-partners/apple-pay.svg'
export const veeLogoAfterpay = '/images/tech-partners/afterpay.svg'
export const veeLogoNetlifyMask = '/images/tech-partners/netlify.svg'
export const veeLogoNetlify = '/images/tech-partners/netlify.svg'
export const veeLogoVercel = '/images/archive/vercel.svg'
export const veeLogoAci = '/images/tech-partners/aci-payon.svg'
export const veeLogoSyte = '/images/tech-partners/syte.svg'
export const veeLogoBazaarvoice = '/images/tech-partners/bazaarvoice.svg'
