/** Figma MCP — SDK / API integrations logo strip */
export const veeLogoSalesforce = '/images/logo-exports/gray/salesforce.svg'
export const veeLogoShopifyPlus = '/images/logo-exports/gray/shopify-plus.svg'
export const veeLogoSap = '/images/logo-exports/gray/sap.svg'
export const veeLogoMagento = '/images/logo-exports/gray/magento.svg'
export const veeLogoApplePay = '/images/logo-exports/gray/apple-pay.svg'
export const veeLogoAfterpay = '/images/logo-exports/gray/afterpay.svg'
export const veeLogoNetlifyMask = '/images/tech-partners/netlify.svg'
export const veeLogoNetlify = '/images/tech-partners/netlify.svg'
export const veeLogoVercel = '/images/logo-exports/gray/vercel.svg'
export const veeLogoAci = '/images/logo-exports/gray/aci-payon.svg'
export const veeLogoSyte = '/images/logo-exports/gray/syte.svg'
export const veeLogoBazaarvoice = '/images/logo-exports/gray/bazaarvoice.svg'
