import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import localFont from 'next/font/local'

import "./globals.css";
import "swiper/css";
import "swiper/css/navigation";

const mainFont = localFont({
  src:'../public/fonts/Uncut-Sans/Webfonts/UncutSans-Regular.woff2',
  display:'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.className} antialiased`}
      >
        <Header/>
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
